version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/localdb
      - SPRING_DATASOURCE_USERNAME=localdb
      - SPRING_DATASOURCE_PASSWORD=localdb
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres"
    environment:
      - POSTGRES_DB=localdb
      - POSTGRES_USER=localdb
      - POSTGRES_PASSWORD=localdb
    ports:
      - '5432:5432'