version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/localdb
      SPRING_DATASOURCE_USERNAME: localdb
      SPRING_DATASOURCE_PASSWORD: localdb
      LOGSTASH_URL: logstash:5000
      SPRING_APPLICATION_NAME: q-unite-api
      JWT_SECRET: Sup4rSecr0t!2
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 1800
      CLIENT_WEB_URL: http://localhost:5173
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
    networks:
      - backend
  postgres_db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: localdb
      POSTGRES_PASSWORD: localdb
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    external: true