spring:
  # JPA properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # Flyway
  flyway:
    enabled: false
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/queue
server:
  servlet:
    context-path: "/api/v1"
