spring:
  application:
    name: qunite-api
  # JPA properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # Flyway
  flyway:
    enabled: false
client:
  web:
    url: "http://localhost:5173"