spring:
  application:
    name: qunite-api
  # JPA properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # Flyway
  flyway:
    enabled: false
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/queue
jwt:
  secret: "secret"