spring:
  application:
    name: qunite-api
  # JPA properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # Flyway
  flyway:
    enabled: false
jwt:
  secret: "topSecret"
  access-token-expiration-time: 1800
client:
  web:
    url: http://localhost:5173