spring:
  # JPA properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # Flyway
  flyway:
    enabled: false
  # Datasource todo
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
# Swagger path
springdoc:
  api-docs:
    path: /api-docs
