name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Build Job
        uses: ./.github/workflows/build.yml
        with:
          branch: ${{ github.event.pull_request.head.ref }}
