name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    steps:
      - name: Trigger Build Job
        uses: ./maven-build.yml
        with:
          branch: dockerfile
